### PR TITLE
Changed FormulaValue to <T extends Record<string, any>>

### PR DESCRIPTION
**Pull request by sserdyuk**
Added a global default type definition

### CODE REVIEW

**Comment by sserdyuk** [comment]
I get about a dozen of lint warnings for "any" type, but that seems to be unrelated to the change in form value typing.

I ran:
-  `npm run nx test svelte-formula` and all tests passed.
- `npm run start formula-app --rollupConfig=apps/formula-app/rollup.config.js` and it started but I wasn't sure what to do
- `npm run build svelte-formula --skip-nx-cache` and it built

**Comment by tanepiper** [comment]
@sserdyuk just wanted to check in and say I'll merge this and release it later today! I have some thing I need to do today before I'll be in front of a computer, but will do it then. I'm actually doing a talk about Formula for Svelte Summit so want to get this out the way.

**Comment by sserdyuk** [comment]
@tanepiper Great! Looking forward to the talk.

**Comment by tanepiper** [comment]
@sserdyuk Published as 0.11.0

**Pull request merged**
