### PR TITLE
Provide correct passwordMatch property name in docs

### PR DESCRIPTION
**Pull request by phaleth**
At first I thought svelte-formula isn't functional as I went straight for the complex form example in the docs. Afterwards I've tried other svelte form libs and finally circled back to svelte-formula and the same example just to find there is a mistake in a property name. This PR attempts to fix that mistake.

### CODE REVIEW

**Comment by nr1995** [comment]
@phaleth 
Hey are you the guy I used to ask for help about AHK on Telegram when I lived in China but then lost touch with?

**Comment by phaleth** [comment]
@nr1995 yeah, find me on IRC libera network in `#bun` channel. Telegram has blocked me.

I wonder if this pull request can be reopened? Sorry for being off topic.

**Comment by tanepiper** [comment]
@phaleth As it's a docs issue it's not been a priority, but I'm deprecating this library anyway in preference of https://github.com/web-helpers/formula - it's the same library but moved to `nanostores` instead of Svelte.  Along with it a new web component for wrapping forms.

**Comment by phaleth** [comment]
Ahh, ok @tanepiper, thank you for the reply and sorry again about hijacking this PR
I guess if you could re-open this PR and let me rebase then we could merge the PR just so your project gets a contribution.
Anyways, back when I created this PR I was just messing around with svelte-formula, but then I ended up making two pretty large forms that are still used in production to this day and I'm not gonna bother myself replacing those two forms  :smile:

**Comment by tanepiper** [comment]
> Ahh, ok @tanepiper, thank you for the reply and sorry again about hijacking this PR
> I guess if you could re-open this PR and let me rebase then we could merge the PR just so your project gets a contribution.
> Anyways, back when I created this PR I was just messing around with svelte-formula, but then I ended up making two pretty large forms that are still used in production to this day and I'm not gonna bother myself replacing those two forms  :smile: 

Nice to hear it's being used in production. In that case, if there are any issues you'd like to fix I'm happy to merge and release as a final release for this.

**Pull request closed without merging**
